<?php

declare(strict_types=1);

namespace Netresearch\NrRepurpose\Generator;

use Netresearch\NrLlm\Service\BudgetServiceInterface;
use Netresearch\NrLlm\Service\Feature\CompletionServiceInterface;
use Netresearch\NrLlm\Service\Option\ChatOptions;
use Netresearch\NrLlm\Specialized\Option\SpeechSynthesisOptions;
use Netresearch\NrRepurpose\Domain\Enum\ArtifactStatus;
use Netresearch\NrRepurpose\Domain\Enum\ArtifactType;
use Netresearch\NrRepurpose\Domain\ValueObject\Persona;
use Netresearch\NrRepurpose\Generator\Speech\SpeechSynthesizerInterface;
use Netresearch\NrRepurpose\Generator\Support\WebVttBuilder;
use Netresearch\NrRepurpose\Persistence\JobProcessingRepository;
use Netresearch\NrRepurpose\Pipeline\GenerationContext;
use Netresearch\NrRepurpose\Rendering\AudioStitcherInterface;
use Netresearch\NrRepurpose\Resource\JobFileStorage;
use Psr\Log\LoggerInterface;

/**
 * Builds a two-host podcast: an LLM dialogue script (length follows document scope),
 * one TTS call per turn (Host A=nova, Host B=onyx, mp3), a stitched mp3, a speaker-tagged
 * transcript and a WebVTT subtitle file whose cue times come from measured segment durations.
 *
 * When the job selected persona snippets (1-3), the dialogue prompt describes each persona
 * and the speakers carry the persona names; each persona speaks with its metadata TTS voice
 * (when it is a known synthesizer voice) or the configured host voices round-robin. Without
 * personas the two-host behavior above is unchanged.
 *
 * The dialogue script is generated by the budget-aware CompletionService (the BudgetMiddleware
 * guards it via ChatOptions->beUserUid). Each TTS call is a Specialized call that is NOT
 * middleware-guarded, so it is gated manually by BudgetService::check() + isAvailable().
 */
final class PodcastGenerator extends AbstractGenerator
{
    private const VOICE_HOST_A = 'nova';
    private const VOICE_HOST_B = 'onyx';
    // Mirrors the model OpenAiSpeechSynthesizer passes to nr-llm's TextToSpeechService.
    private const TTS_MODEL = 'tts-1';
    private const TTS_COST_PER_TURN = 0.015;
    private const SCRIPT_COST = 0.02;

    /**
     * Each turn is one Specialized TTS HTTP call. OpenAI occasionally stalls a request (a slow
     * response or a stale keep-alive connection); a single retry issues a fresh request — usually
     * on a new connection — and almost always recovers. A turn that still fails is skipped rather
     * than failing the whole podcast, so one flaky call can't lose a 15-turn episode.
     */
    private const TTS_MAX_ATTEMPTS = 2;

    public function __construct(
        JobProcessingRepository $jobs,
        BudgetServiceInterface $budget,
        LoggerInterface $logger,
        private readonly CompletionServiceInterface $completion,
        private readonly SpeechSynthesizerInterface $speech,
        private readonly AudioStitcherInterface $stitcher,
        private readonly JobFileStorage $fileStorage,
        private readonly WebVttBuilder $vttBuilder,
    ) {
        parent::__construct($jobs, $budget, $logger);
    }

    public function supports(GenerationContext $ctx): bool
    {
        return (bool) ($ctx->jobRow['want_podcast'] ?? false);
    }

    public function generate(GenerationContext $ctx): bool
    {
        $jobUid = $ctx->jobUid();
        $artifactUid = $this->jobs->insertArtifact($jobUid, ArtifactType::Podcast, 'default', 0, ArtifactStatus::Pending);

        // Budget-guarded availability check for the Specialized TTS calls up front.
        $turnCount = max(1, count($ctx->brief->keyPoints) + count($ctx->brief->sections) + 2);
        $plannedTtsCost = self::TTS_COST_PER_TURN * $turnCount;
        if (!$this->specializedAllowed($ctx, $plannedTtsCost, $this->speech->isAvailable())) {
            $this->failArtifact($artifactUid, $jobUid, 'AI budget exhausted or speech synthesis unavailable');

            return false;
        }

        try {
            $ctx->progress?->step('Podcast: writing script', 0.05);
            $personaVoices = $this->personaVoices($ctx->snippets->personas);
            $dialogue = $this->buildDialogue($ctx, $personaVoices);
            $turns = $dialogue['turns'];
            if ($turns === []) {
                $this->failArtifact($artifactUid, $jobUid, 'LLM produced no dialogue turns');

                return false;
            }

            $tmpDir = $this->makeTempDir();
            $segmentPaths = [];
            $vttSegments = [];
            $transcriptLines = [];

            $totalTurns = count($turns);
            foreach ($turns as $i => $turn) {
                $ctx->progress?->step(
                    sprintf('Podcast: voicing segment %d/%d', $i + 1, $totalTurns),
                    0.1 + 0.8 * $i / $totalTurns,
                );
                $segmentPath = sprintf('%s/turn-%d.mp3', $tmpDir, $i);
                if (!$this->synthesizeWithRetry($turn['text'], $turn['voice'], $segmentPath, $jobUid, $i)) {
                    continue;
                }
                $segmentPaths[] = $segmentPath;
                $vttSegments[] = [
                    'speaker' => $turn['speaker'],
                    'text' => $turn['text'],
                    'durationSeconds' => $this->stitcher->probeDurationSeconds($segmentPath),
                ];
                $transcriptLines[] = $turn['speaker'] . ': ' . $turn['text'];
            }

            if ($segmentPaths === []) {
                $this->failArtifact($artifactUid, $jobUid, 'All podcast TTS turns failed');

                return false;
            }

            $ctx->progress?->step('Podcast: stitching audio', 0.9);
            $mp3Path = $tmpDir . '/podcast.mp3';
            $this->stitcher->concat($segmentPaths, $mp3Path);

            $transcript = implode("\n", $transcriptLines);
            $vtt = $this->vttBuilder->build($vttSegments);

            $mp3File = $this->fileStorage->store((string) file_get_contents($mp3Path), 'podcast.mp3');
            $vttFile = $this->fileStorage->store($vtt, 'podcast.vtt');

            $this->jobs->updateArtifact($artifactUid, [
                'file_uid' => $mp3File->getUid(),
                'subtitle_file_uid' => $vttFile->getUid(),
                'script_text' => $transcript,
                'metadata' => json_encode(
                    $this->buildMetadata($personaVoices, count($turns), $dialogue['system'], $dialogue['user']),
                    JSON_THROW_ON_ERROR,
                ),
                'status' => ArtifactStatus::Done->value,
            ]);

            return true;
        } catch (\Throwable $e) {
            $this->failArtifact($artifactUid, $jobUid, 'Podcast generation error: ' . $e->getMessage());

            return false;
        }
    }

    /**
     * Synthesize one turn, retrying a transient TTS failure once. Returns false when every
     * attempt failed so the caller can skip the turn and keep the rest of the episode.
     */
    private function synthesizeWithRetry(string $text, string $voice, string $segmentPath, int $jobUid, int $turnIndex): bool
    {
        for ($attempt = 1; $attempt <= self::TTS_MAX_ATTEMPTS; $attempt++) {
            try {
                $this->speech->synthesizeToFile($text, $voice, $segmentPath);

                return true;
            } catch (\Throwable $e) {
                $this->logger->warning('Podcast TTS turn failed', [
                    'job' => $jobUid,
                    'turn' => $turnIndex,
                    'attempt' => $attempt,
                    'reason' => $e->getMessage(),
                ]);
            }
        }

        return false;
    }

    /**
     * Build the dialogue and hand back the exact prompts used, so the artifact metadata
     * can record them verbatim (transparency: prompts.system / prompts.user).
     *
     * @param array<string, string> $personaVoices persona name => TTS voice (empty: two-host mode)
     *
     * @return array{turns: list<array{speaker: string, text: string, voice: string}>, system: string, user: string}
     */
    private function buildDialogue(GenerationContext $ctx, array $personaVoices): array
    {
        return $personaVoices === []
            ? $this->buildTwoHostDialogue($ctx)
            : $this->buildPersonaDialogue($ctx, $personaVoices);
    }

    /**
     * The pre-snippet default: Host A / Host B with the configured voices (unchanged).
     *
     * @return array{turns: list<array{speaker: string, text: string, voice: string}>, system: string, user: string}
     */
    private function buildTwoHostDialogue(GenerationContext $ctx): array
    {
        $brief = $ctx->brief;
        $keyPoints = implode("\n- ", $brief->keyPoints);
        $prompt = sprintf(
            "Title: %s\nSummary: %s\nAudience: %s\nKey points:\n- %s\n\n"
            . 'Write a lively two-host podcast dialogue (Host A and Host B) that explains this '
            . 'content faithfully to the audience. Keep all facts, numbers and labels accurate. '
            . 'The length must follow the document scope — short for short documents, longer for rich ones. '
            . 'Each turn must be at most 600 characters.',
            $brief->title,
            $brief->summary,
            $brief->audience,
            $keyPoints,
        );

        $systemPrompt = sprintf(
            'You are a podcast scriptwriter. Write in language code "%s". Output ONLY valid JSON '
            . 'of the shape {"turns":[{"speaker":"Host A"|"Host B","text":"..."}]}.',
            $brief->language,
        );
        $options = new ChatOptions(
            temperature: 0.6,
            responseFormat: 'json',
            systemPrompt: $systemPrompt,
            beUserUid: $ctx->beUser,
            plannedCost: self::SCRIPT_COST,
        );

        $data = $this->completion->completeJson($prompt, $options);
        $rawTurns = is_array($data['turns'] ?? null) ? $data['turns'] : [];

        $turns = [];
        foreach ($rawTurns as $raw) {
            $speaker = (string) ($raw['speaker'] ?? 'Host A');
            $text = trim((string) ($raw['text'] ?? ''));
            if ($text === '') {
                continue;
            }
            $turns[] = [
                'speaker' => $speaker,
                'text' => mb_substr($text, 0, 4096),
                'voice' => $speaker === 'Host B' ? self::VOICE_HOST_B : self::VOICE_HOST_A,
            ];
        }

        return ['turns' => $turns, 'system' => $systemPrompt, 'user' => $prompt];
    }

    /**
     * Persona mode: the prompt describes each selected persona and the JSON shape uses the
     * persona names as speakers. A turn from an unknown speaker is attributed to the first
     * persona so a slightly non-compliant LLM answer still synthesizes.
     *
     * @param array<string, string> $personaVoices persona name => TTS voice
     *
     * @return array{turns: list<array{speaker: string, text: string, voice: string}>, system: string, user: string}
     */
    private function buildPersonaDialogue(GenerationContext $ctx, array $personaVoices): array
    {
        $brief = $ctx->brief;
        $keyPoints = implode("\n- ", $brief->keyPoints);
        $personaLines = array_map(
            static fn (Persona $persona): string => sprintf('- %s: %s', $persona->name, $persona->description),
            $ctx->snippets->personas,
        );
        $names = array_keys($personaVoices);

        $prompt = sprintf(
            "Title: %s\nSummary: %s\nAudience: %s\nKey points:\n- %s\n\nHosts:\n%s\n\n"
            . 'Write a lively podcast dialogue between the hosts described above that explains this '
            . 'content faithfully to the audience. Keep every host in character with their persona '
            . 'description. Keep all facts, numbers and labels accurate. '
            . 'The length must follow the document scope — short for short documents, longer for rich ones. '
            . 'Each turn must be at most 600 characters.',
            $brief->title,
            $brief->summary,
            $brief->audience,
            $keyPoints,
            implode("\n", $personaLines),
        );

        // JSON-encode each speaker name: a quote/backslash in a persona name must not be able
        // to malform the JSON-shape constraint or the "|" alternation between the names. The
        // int side of the union covers PHP's array-key casting of numeric persona names.
        $speakerAlternation = implode('|', array_map(
            static fn (string|int $name): string => json_encode((string) $name, JSON_THROW_ON_ERROR | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES),
            $names,
        ));

        $systemPrompt = sprintf(
            'You are a podcast scriptwriter. Write in language code "%s". Output ONLY valid JSON '
            . 'of the shape {"turns":[{"speaker":%s,"text":"..."}]}.',
            $brief->language,
            $speakerAlternation,
        );
        $options = new ChatOptions(
            temperature: 0.6,
            responseFormat: 'json',
            systemPrompt: $systemPrompt,
            beUserUid: $ctx->beUser,
            plannedCost: self::SCRIPT_COST,
        );

        $data = $this->completion->completeJson($prompt, $options);
        $rawTurns = is_array($data['turns'] ?? null) ? $data['turns'] : [];

        $turns = [];
        foreach ($rawTurns as $raw) {
            $speaker = (string) ($raw['speaker'] ?? '');
            if (!isset($personaVoices[$speaker])) {
                $speaker = $names[0];
            }
            $text = trim((string) ($raw['text'] ?? ''));
            if ($text === '') {
                continue;
            }
            $turns[] = [
                'speaker' => $speaker,
                'text' => mb_substr($text, 0, 4096),
                'voice' => $personaVoices[$speaker],
            ];
        }

        return ['turns' => $turns, 'system' => $systemPrompt, 'user' => $prompt];
    }

    /**
     * Map each persona to its TTS voice: the snippet's metadata voice when it is one of the
     * synthesizer's known voices, otherwise the configured host voices round-robin (A, B, A).
     *
     * Keying by name is safe: PromptSnippetResolver guarantees persona names are non-empty
     * and unique (duplicates are suffixed), so no entry can overwrite another and the keys
     * match the prompt's host list one-to-one, in order.
     *
     * @param list<Persona> $personas
     *
     * @return array<string, string> persona name => voice (empty when no personas are selected)
     */
    private function personaVoices(array $personas): array
    {
        $fallback = [self::VOICE_HOST_A, self::VOICE_HOST_B];
        $known = SpeechSynthesisOptions::getAvailableVoices();
        $voices = [];
        foreach (array_values($personas) as $i => $persona) {
            $voices[$persona->name] = ($persona->voice !== null && in_array($persona->voice, $known, true))
                ? $persona->voice
                : $fallback[$i % 2];
        }

        return $voices;
    }

    /**
     * @param array<string, string> $personaVoices
     *
     * @return array<string, mixed>
     */
    private function buildMetadata(array $personaVoices, int $turnCount, string $systemPrompt, string $userPrompt): array
    {
        $voiceMap = $personaVoices === []
            ? ['Host A' => self::VOICE_HOST_A, 'Host B' => self::VOICE_HOST_B]
            : $personaVoices;
        $metadata = [
            'voices' => array_values($voiceMap),
            'turns' => $turnCount,
            'ttsModel' => self::TTS_MODEL,
            'prompts' => $this->promptsMetadata(
                system: $systemPrompt,
                user: $userPrompt,
                ttsModel: self::TTS_MODEL,
                voices: $voiceMap,
            ),
        ];
        if ($personaVoices !== []) {
            $metadata['personas'] = array_keys($personaVoices);
        }

        return $metadata;
    }
}
