<?php

declare(strict_types=1);

namespace Netresearch\NrRepurpose\Generator;

use Netresearch\NrLlm\Service\BudgetServiceInterface;
use Netresearch\NrLlm\Service\Feature\CompletionServiceInterface;
use Netresearch\NrLlm\Service\Option\ChatOptions;
use Netresearch\NrRepurpose\Domain\Enum\ArtifactStatus;
use Netresearch\NrRepurpose\Domain\Enum\ArtifactType;
use Netresearch\NrRepurpose\Generator\Speech\SpeechSynthesizerInterface;
use Netresearch\NrRepurpose\Generator\Support\WebVttBuilder;
use Netresearch\NrRepurpose\Persistence\JobProcessingRepository;
use Netresearch\NrRepurpose\Pipeline\GenerationContext;
use Netresearch\NrRepurpose\Rendering\AudioStitcherInterface;
use Netresearch\NrRepurpose\Resource\JobFileStorage;
use Psr\Log\LoggerInterface;

/**
 * Builds a two-host podcast: an LLM dialogue script (length follows document scope),
 * one TTS call per turn (Host A=nova, Host B=onyx, mp3), a stitched mp3, a speaker-tagged
 * transcript and a WebVTT subtitle file whose cue times come from measured segment durations.
 *
 * The dialogue script is generated by the budget-aware CompletionService (the BudgetMiddleware
 * guards it via ChatOptions->beUserUid). Each TTS call is a Specialized call that is NOT
 * middleware-guarded, so it is gated manually by BudgetService::check() + isAvailable().
 */
final class PodcastGenerator extends AbstractGenerator
{
    private const VOICE_HOST_A = 'nova';
    private const VOICE_HOST_B = 'onyx';
    private const TTS_COST_PER_TURN = 0.015;
    private const SCRIPT_COST = 0.02;

    public function __construct(
        JobProcessingRepository $jobs,
        BudgetServiceInterface $budget,
        LoggerInterface $logger,
        private readonly CompletionServiceInterface $completion,
        private readonly SpeechSynthesizerInterface $speech,
        private readonly AudioStitcherInterface $stitcher,
        private readonly JobFileStorage $fileStorage,
        private readonly WebVttBuilder $vttBuilder,
    ) {
        parent::__construct($jobs, $budget, $logger);
    }

    public function supports(GenerationContext $ctx): bool
    {
        return (bool) ($ctx->jobRow['want_podcast'] ?? false);
    }

    public function generate(GenerationContext $ctx): bool
    {
        $jobUid = $ctx->jobUid();
        $artifactUid = $this->jobs->insertArtifact($jobUid, ArtifactType::Podcast, 'default', 0, ArtifactStatus::Pending);

        // Budget-guarded availability check for the Specialized TTS calls up front.
        $turnCount = max(1, count($ctx->brief->keyPoints) + count($ctx->brief->sections) + 2);
        $plannedTtsCost = self::TTS_COST_PER_TURN * $turnCount;
        if (!$this->specializedAllowed($ctx, $plannedTtsCost, $this->speech->isAvailable())) {
            $this->failArtifact($artifactUid, $jobUid, 'AI budget exhausted or speech synthesis unavailable');

            return false;
        }

        try {
            $turns = $this->buildDialogue($ctx);
            if ($turns === []) {
                $this->failArtifact($artifactUid, $jobUid, 'LLM produced no dialogue turns');

                return false;
            }

            $tmpDir = $this->makeTempDir();
            $segmentPaths = [];
            $vttSegments = [];
            $transcriptLines = [];

            foreach ($turns as $i => $turn) {
                $segmentPath = sprintf('%s/turn-%d.mp3', $tmpDir, $i);
                $this->speech->synthesizeToFile($turn['text'], $turn['voice'], $segmentPath);
                $segmentPaths[] = $segmentPath;
                $vttSegments[] = [
                    'speaker' => $turn['speaker'],
                    'text' => $turn['text'],
                    'durationSeconds' => $this->stitcher->probeDurationSeconds($segmentPath),
                ];
                $transcriptLines[] = $turn['speaker'] . ': ' . $turn['text'];
            }

            $mp3Path = $tmpDir . '/podcast.mp3';
            $this->stitcher->concat($segmentPaths, $mp3Path);

            $transcript = implode("\n", $transcriptLines);
            $vtt = $this->vttBuilder->build($vttSegments);

            $mp3File = $this->fileStorage->store((string) file_get_contents($mp3Path), 'podcast.mp3');
            $vttFile = $this->fileStorage->store($vtt, 'podcast.vtt');

            $this->jobs->updateArtifact($artifactUid, [
                'file_uid' => $mp3File->getUid(),
                'subtitle_file_uid' => $vttFile->getUid(),
                'script_text' => $transcript,
                'metadata' => json_encode([
                    'voices' => [self::VOICE_HOST_A, self::VOICE_HOST_B],
                    'turns' => count($turns),
                    'ttsModel' => 'tts-1',
                ], JSON_THROW_ON_ERROR),
                'status' => ArtifactStatus::Done->value,
            ]);

            return true;
        } catch (\Throwable $e) {
            $this->failArtifact($artifactUid, $jobUid, 'Podcast generation error: ' . $e->getMessage());

            return false;
        }
    }

    /**
     * @return list<array{speaker: string, text: string, voice: string}>
     */
    private function buildDialogue(GenerationContext $ctx): array
    {
        $brief = $ctx->brief;
        $keyPoints = implode("\n- ", $brief->keyPoints);
        $prompt = sprintf(
            "Title: %s\nSummary: %s\nAudience: %s\nKey points:\n- %s\n\n"
            . 'Write a lively two-host podcast dialogue (Host A and Host B) that explains this '
            . 'content faithfully to the audience. Keep all facts, numbers and labels accurate. '
            . 'The length must follow the document scope — short for short documents, longer for rich ones. '
            . 'Each turn must be at most 600 characters.',
            $brief->title,
            $brief->summary,
            $brief->audience,
            $keyPoints,
        );

        $options = new ChatOptions(
            temperature: 0.6,
            responseFormat: 'json',
            systemPrompt: sprintf(
                'You are a podcast scriptwriter. Write in language code "%s". Output ONLY valid JSON '
                . 'of the shape {"turns":[{"speaker":"Host A"|"Host B","text":"..."}]}.',
                $brief->language,
            ),
            beUserUid: $ctx->beUser,
            plannedCost: self::SCRIPT_COST,
        );

        $data = $this->completion->completeJson($prompt, $options);
        $rawTurns = is_array($data['turns'] ?? null) ? $data['turns'] : [];

        $turns = [];
        foreach ($rawTurns as $raw) {
            $speaker = (string) ($raw['speaker'] ?? 'Host A');
            $text = trim((string) ($raw['text'] ?? ''));
            if ($text === '') {
                continue;
            }
            $turns[] = [
                'speaker' => $speaker,
                'text' => mb_substr($text, 0, 4096),
                'voice' => $speaker === 'Host B' ? self::VOICE_HOST_B : self::VOICE_HOST_A,
            ];
        }

        return $turns;
    }
}
