<?php

/*
 * Copyright (c) 2025-2026 Netresearch DTT GmbH
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

declare(strict_types=1);

namespace Netresearch\NrRepurpose\Tests\Unit\Provenance;

use Netresearch\NrRepurpose\Provenance\AiContentMarker;
use Netresearch\NrRepurpose\Provenance\AiProvenance;
use Netresearch\NrRepurpose\Provenance\DigitalSourceType;
use Netresearch\NrRepurpose\Rendering\GdImageCompositor;
use Netresearch\NrRepurpose\Rendering\RenderingException;
use Netresearch\NrRepurpose\Tests\Unit\Fixture\AiMarkerReader;
use PHPUnit\Framework\TestCase;

/**
 * Reads the markers back out of real generated bytes:
 *
 * - Tests/Fixtures/Image/chromium-render.png: written by the extension's own
 *   Resources/Private/NodeRenderer/render.cjs (Playwright + Chromium), the path of the
 *   Schaubild html variant and the flat story slides.
 * - a PNG written by GdImageCompositor in the test, the path of html_bg and the story
 *   slides on an AI background.
 * - Tests/Fixtures/Audio/stitched-podcast.mp3: two libmp3lame segments joined with the
 *   exact command FfmpegAudioStitcher runs (`-f concat -safe 0 -i list -c copy`), which
 *   writes an ID3v2.4 tag holding ffmpeg's TSSE.
 * - Tests/Fixtures/Audio/tts-segment-without-id3.mp3: a segment without any ID3 tag.
 */
final class AiContentMarkerTest extends TestCase
{
    private const FIXTURES = __DIR__ . '/../../Fixtures/';

    private function provenance(DigitalSourceType $type = DigitalSourceType::CompositeWithTrainedAlgorithmicMedia): AiProvenance
    {
        return new AiProvenance('nr_repurpose 9.9.9', $type, ['image' => 'image-model-x']);
    }

    private function fixture(string $path): string
    {
        return (string) file_get_contents(self::FIXTURES . $path);
    }

    public function testChromiumPngCarriesSoftwareCommentAndXmpDigitalSourceType(): void
    {
        $marked = (new AiContentMarker())->markPng($this->fixture('Image/chromium-render.png'), $this->provenance());

        $text = AiMarkerReader::pngText($marked);
        self::assertSame('nr_repurpose 9.9.9', $text['Software'] ?? null);
        self::assertSame(
            'AI-generated with nr_repurpose 9.9.9 (IPTC digital source type: compositeWithTrainedAlgorithmicMedia; models: image=image-model-x).',
            $text['Comment'] ?? null,
        );

        $xmp = AiMarkerReader::pngXmp($marked);
        self::assertNotNull($xmp);
        self::assertSame(DigitalSourceType::CompositeWithTrainedAlgorithmicMedia->value, AiMarkerReader::xmpDigitalSourceType($xmp));
    }

    public function testPngStaysValidAndItsImageDataIsUnchanged(): void
    {
        $original = $this->fixture('Image/chromium-render.png');
        $marked   = (new AiContentMarker())->markPng($original, $this->provenance());

        $chunks = AiMarkerReader::pngChunks($marked);
        foreach ($chunks as $chunk) {
            self::assertTrue($chunk['crcValid'], $chunk['type'] . ' has a wrong CRC');
        }

        $types = array_column($chunks, 'type');
        self::assertSame('IHDR', $types[0]);
        self::assertSame('IEND', $types[array_key_last($types)]);
        // The metadata sits before the image data, where XMP-in-PNG readers look.
        self::assertLessThan(array_search('IDAT', $types, true), array_search('iTXt', $types, true));

        // Removing exactly the three added chunks gives back the original chunk list.
        $withoutMarker = array_values(array_filter($chunks, static fn (array $c): bool => !in_array($c['type'], ['tEXt', 'iTXt'], true)));
        self::assertEquals(AiMarkerReader::pngChunks($original), $withoutMarker);
        self::assertSame(['IHDR', 'tEXt', 'tEXt', 'iTXt'], array_slice($types, 0, 4));
    }

    public function testMarkedPngStillDecodes(): void
    {
        if (!function_exists('imagecreatefromstring')) {
            self::markTestSkipped('ext-gd is not available');
        }

        $marked = (new AiContentMarker())->markPng($this->fixture('Image/chromium-render.png'), $this->provenance());
        $image  = @imagecreatefromstring($marked);

        self::assertNotFalse($image);
        self::assertSame(96, imagesx($image));
        self::assertSame(48, imagesy($image));
    }

    public function testGdCompositorOutputIsMarked(): void
    {
        if (!function_exists('imagecreatetruecolor')) {
            self::markTestSkipped('ext-gd is not available');
        }

        $dir = sys_get_temp_dir() . '/nrrepurpose_marker_' . bin2hex(random_bytes(4));
        mkdir($dir);
        try {
            $background = imagecreatetruecolor(40, 20);
            imagepng($background, $dir . '/bg.png');
            $foreground = imagecreatetruecolor(20, 10);
            imagesavealpha($foreground, true);
            imagepng($foreground, $dir . '/fg.png');
            (new GdImageCompositor())->overlay($dir . '/bg.png', $dir . '/fg.png', $dir . '/out.png');

            $marked = (new AiContentMarker())->markPng((string) file_get_contents($dir . '/out.png'), $this->provenance(DigitalSourceType::TrainedAlgorithmicMedia));
        } finally {
            array_map(unlink(...), glob($dir . '/*') ?: []);
            rmdir($dir);
        }

        $xmp = AiMarkerReader::pngXmp($marked);
        self::assertNotNull($xmp);
        self::assertSame(DigitalSourceType::TrainedAlgorithmicMedia->value, AiMarkerReader::xmpDigitalSourceType($xmp));
    }

    public function testPngWithAC2paManifestIsLeftByteIdentical(): void
    {
        $original = $this->fixture('Image/chromium-render.png');
        // A caBX chunk (C2PA manifest store) right after IHDR, as a signed image carries it.
        $data     = 'jumb-manifest-placeholder';
        $caBx     = pack('N', strlen($data)) . 'caBX' . $data . pack('N', crc32('caBX' . $data));
        $withC2pa = substr($original, 0, 33) . $caBx . substr($original, 33);

        self::assertSame($withC2pa, (new AiContentMarker())->markPng($withC2pa, $this->provenance()));
    }

    public function testNonPngBytesAreRefused(): void
    {
        $this->expectException(RenderingException::class);
        $this->expectExceptionCode(1790000501);

        (new AiContentMarker())->markPng("\xFF\xD8\xFF\xE0 a jpeg", $this->provenance());
    }

    public function testStitchedMp3GetsAnId3v23TagWithTheAiFramesInPlaceOfFfmpegsTag(): void
    {
        $original = $this->fixture('Audio/stitched-podcast.mp3');
        $before   = AiMarkerReader::id3($original);
        self::assertSame(4, $before['version'], 'fixture premise: ffmpeg writes ID3v2.4');

        $marked = (new AiContentMarker())->markMp3($original, $this->provenance(DigitalSourceType::TrainedAlgorithmicMedia));
        $tag    = AiMarkerReader::id3($marked);

        self::assertSame(3, $tag['version']);
        self::assertSame(['TXXX', 'TXXX', 'TSSE', 'COMM'], array_column($tag['frames'], 'id'));
        self::assertSame(
            ['AI-generated' => 'true', 'DigitalSourceType' => DigitalSourceType::TrainedAlgorithmicMedia->value],
            AiMarkerReader::id3UserText($tag['frames']),
        );
        self::assertSame("\0nr_repurpose 9.9.9", $tag['frames'][2]['data']);
        self::assertSame(
            "\0eng\0AI-generated with nr_repurpose 9.9.9 (IPTC digital source type: trainedAlgorithmicMedia; models: image=image-model-x).",
            $tag['frames'][3]['data'],
        );
        // The audio frames are untouched; only the tag in front of them was replaced.
        self::assertSame($before['audio'], $tag['audio']);
        self::assertStringNotContainsString('Lavf', substr($marked, 0, 200));
    }

    public function testMp3WithoutATagGetsOneAndKeepsEveryAudioByte(): void
    {
        $original = $this->fixture('Audio/tts-segment-without-id3.mp3');
        self::assertStringStartsNotWith('ID3', $original, 'fixture premise: no tag');

        $tag = AiMarkerReader::id3((new AiContentMarker())->markMp3($original, $this->provenance()));

        self::assertSame('true', AiMarkerReader::id3UserText($tag['frames'])['AI-generated'] ?? null);
        self::assertSame($original, $tag['audio']);
    }

    public function testNonMp3BytesAreRefused(): void
    {
        $this->expectException(RenderingException::class);
        $this->expectExceptionCode(1790000503);

        (new AiContentMarker())->markMp3('WEBVTT', $this->provenance());
    }

    public function testMarkDispatchesOnTheFileExtension(): void
    {
        $marker = new AiContentMarker();
        $png    = $this->fixture('Image/chromium-render.png');
        $mp3    = $this->fixture('Audio/tts-segment-without-id3.mp3');

        self::assertNotNull(AiMarkerReader::pngXmp($marker->mark($png, 'story-slide-1.PNG', $this->provenance())));
        self::assertStringStartsWith('ID3', $marker->mark($mp3, 'podcast.mp3', $this->provenance()));
        self::assertSame("WEBVTT\n", $marker->mark("WEBVTT\n", 'podcast.vtt', $this->provenance()));
    }
}
