name: ddev-nr-repurpose
services:
  db:
    build:
      context: /home/sme/p/nr-repurpose/main/.ddev/.dbimageBuild
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ddev/ddev-dbserver-mariadb-11.4:v1.25.2
        gid: "1000"
        uid: "1000"
        username: sme
      labels:
        com.ddev.app-type: typo3
        com.ddev.approot: /home/sme/p/nr-repurpose/main
        com.ddev.platform: ddev
        com.ddev.site-name: nr-repurpose
        com.ddev.webtag: v1.25.2
    cap_add:
      - SYS_NICE
    command: []
    container_name: ddev-nr-repurpose-db
    environment:
      BITNAMI_VOLUME_DIR: ""
      COLUMNS: "80"
      DDEV_DATABASE: mariadb:11.4
      DDEV_DATABASE_FAMILY: mysql
      DDEV_GID: "1000"
      DDEV_GOARCH: amd64
      DDEV_GOOS: linux
      DDEV_HOSTNAME: nr-repurpose.ddev.site
      DDEV_PHP_VERSION: "8.5"
      DDEV_PRIMARY_URL: https://nr-repurpose.ddev.site
      DDEV_PRIMARY_URL_PORT: "443"
      DDEV_PRIMARY_URL_WITHOUT_PORT: https://nr-repurpose.ddev.site
      DDEV_PROJECT: nr-repurpose
      DDEV_PROJECT_TYPE: typo3
      DDEV_ROUTER_HTTP_PORT: "80"
      DDEV_ROUTER_HTTPS_PORT: "443"
      DDEV_SCHEME: https
      DDEV_SITENAME: nr-repurpose
      DDEV_TLD: ddev.site
      DDEV_UID: "1000"
      DDEV_USER: sme
      DDEV_VERSION: v1.25.2
      DOCKER_IP: 127.0.0.1
      HOST_DOCKER_INTERNAL_IP: 192.168.2.24
      IS_DDEV_PROJECT: "true"
      LINES: "24"
      MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/nr-repurpose-db/mysql_history
      PGDATABASE: db
      PGHOST: 127.0.0.1
      PGPASSWORD: db
      PGUSER: db
      POSTGRES_DB: db
      POSTGRES_PASSWORD: db
      POSTGRES_USER: db
      TZ: Europe/Berlin
      USER: sme
    extra_hosts:
      - host.docker.internal=192.168.2.24
    hostname: nr-repurpose-db
    healthcheck:
      test:
        - CMD-SHELL
        - /healthcheck.sh
      timeout: 1m10s
      interval: 1s
      retries: 70
      start_period: 2m0s
      start_interval: 1s
    image: ddev/ddev-dbserver-mariadb-11.4:v1.25.2-nr-repurpose-built
    labels:
      com.ddev.app-type: typo3
      com.ddev.approot: /home/sme/p/nr-repurpose/main
      com.ddev.platform: ddev
      com.ddev.site-name: nr-repurpose
      com.ddev.webtag: v1.25.2
    networks:
      ddev_default: null
      default: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 3306
        protocol: tcp
    restart: "no"
    stop_grace_period: 1m0s
    user: 1000:1000
    volumes:
      - type: volume
        source: database
        target: /var/lib/mysql
        volume:
          nocopy: true
      - type: bind
        source: /home/sme/p/nr-repurpose/main/.ddev
        target: /mnt/ddev_config
        bind: {}
      - type: bind
        source: /home/sme/p/nr-repurpose/main/.ddev/db_snapshots
        target: /mnt/snapshots
        bind: {}
      - type: volume
        source: ddev-global-cache
        target: /mnt/ddev-global-cache
        volume: {}
    working_dir: /home/sme
  web:
    build:
      context: /home/sme/p/nr-repurpose/main/.ddev/.webimageBuild
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ddev/ddev-webserver:v1.25.2
        DDEV_DATABASE: mariadb:11.4
        DDEV_PHP_VERSION: "8.5"
        gid: "1000"
        uid: "1000"
        username: sme
      labels:
        com.ddev.app-type: typo3
        com.ddev.approot: /home/sme/p/nr-repurpose/main
        com.ddev.platform: ddev
        com.ddev.site-name: nr-repurpose
        com.ddev.webtag: v1.25.2
    cap_add:
      - SYS_PTRACE
    command:
      - /pre-start.sh
    container_name: ddev-nr-repurpose-web
    environment:
      ANTHROPIC_API_KEY: ""
      COLUMNS: "80"
      COREPACK_ENABLE_DOWNLOAD_PROMPT: "0"
      COREPACK_HOME: /mnt/ddev-global-cache/corepack
      DDEV_APPROOT: /var/www/html
      DDEV_COMPOSER_ROOT: /var/www/html
      DDEV_DATABASE: mariadb:11.4
      DDEV_DATABASE_FAMILY: mysql
      DDEV_DOCROOT: .Build/Web
      DDEV_FILES_DIR: /var/www/html/.Build/Web/fileadmin
      DDEV_FILES_DIRS: /var/www/html/.Build/Web/fileadmin
      DDEV_GID: "1000"
      DDEV_GOARCH: amd64
      DDEV_GOOS: linux
      DDEV_HOSTNAME: nr-repurpose.ddev.site
      DDEV_MUTAGEN_ENABLED: "false"
      DDEV_PHP_VERSION: "8.5"
      DDEV_PRIMARY_URL: https://nr-repurpose.ddev.site
      DDEV_PRIMARY_URL_PORT: "443"
      DDEV_PRIMARY_URL_WITHOUT_PORT: https://nr-repurpose.ddev.site
      DDEV_PROJECT: nr-repurpose
      DDEV_PROJECT_TYPE: typo3
      DDEV_ROUTER_HTTP_PORT: "80"
      DDEV_ROUTER_HTTPS_PORT: "443"
      DDEV_SCHEME: https
      DDEV_SITENAME: nr-repurpose
      DDEV_TLD: ddev.site
      DDEV_UID: "1000"
      DDEV_USER: sme
      DDEV_VERSION: v1.25.2
      DDEV_WEB_ENTRYPOINT: /mnt/ddev_config/web-entrypoint.d
      DDEV_WEBSERVER_TYPE: apache-fpm
      DDEV_XDEBUG_ENABLED: "false"
      DDEV_XHPROF_MODE: xhgui
      DEPLOY_NAME: local
      DOCKER_IP: 127.0.0.1
      DOCROOT: .Build/Web
      DRUSH_OPTIONS_URI: https://nr-repurpose.ddev.site
      FAL_API_KEY: ""
      GEMINI_API_KEY: ""
      HOST_DOCKER_INTERNAL_IP: 192.168.2.24
      HTTP_EXPOSE: 80:80,8025:8025
      HTTPS_EXPOSE: 443:80,8026:8025
      IS_DDEV_PROJECT: "true"
      LINES: "24"
      MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/nr-repurpose-web/mysql_history
      NODE_EXTRA_CA_CERTS: /mnt/ddev-global-cache/mkcert/rootCA.pem
      OPENAI_API_KEY: ""
      PGDATABASE: db
      PGHOST: db
      PGPASSWORD: db
      PGUSER: db
      PHP_IDE_CONFIG: serverName=nr-repurpose.ddev.site
      SSH_AUTH_SOCK: /home/.ssh-agent/socket
      START_SCRIPT_TIMEOUT: "115"
      TYPO3_CONTEXT: Development
      TZ: Europe/Berlin
      USER: sme
      VIRTUAL_HOST: nr-repurpose.ddev.site
      npm_config_cache: /mnt/ddev-global-cache/npm
    extra_hosts:
      - host.docker.internal=192.168.2.24
    hostname: nr-repurpose-web
    healthcheck:
      test:
        - CMD-SHELL
        - /healthcheck.sh
      timeout: 1m10s
      interval: 1s
      retries: 70
      start_period: 2m0s
      start_interval: 1s
    image: ddev/ddev-webserver:v1.25.2-nr-repurpose-built
    labels:
      com.ddev.app-type: typo3
      com.ddev.approot: /home/sme/p/nr-repurpose/main
      com.ddev.platform: ddev
      com.ddev.site-name: nr-repurpose
      com.ddev.webtag: v1.25.2
    networks:
      ddev_default: null
      default: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 80
        protocol: tcp
      - mode: ingress
        host_ip: 127.0.0.1
        target: 443
        protocol: tcp
      - mode: ingress
        host_ip: 127.0.0.1
        target: 8025
        protocol: tcp
    restart: "no"
    user: 1000:1000
    volumes:
      - type: bind
        source: /home/sme/p/nr-repurpose/main
        target: /var/www/html
        consistency: cached
      - type: bind
        source: /home/sme/p/nr-repurpose/main/.ddev
        target: /mnt/ddev_config
        read_only: true
        bind: {}
      - type: volume
        source: ddev-global-cache
        target: /mnt/ddev-global-cache
        volume: {}
      - type: volume
        source: ddev-ssh-agent_socket_dir
        target: /home/.ssh-agent
        volume: {}
      - type: bind
        source: /home/sme/p/t3x-nr-llm/main
        target: /var/t3x-nr-llm/main
      - type: bind
        source: /home/sme/p/t3x-nr-vault/main
        target: /var/t3x-nr-vault/main
    working_dir: /var/www/html/
  xhgui:
    profiles:
      - xhgui
    container_name: ddev-nr-repurpose-xhgui
    depends_on:
      db:
        condition: service_started
        required: true
    environment:
      DDEV_DATABASE_FAMILY: mysql
      HOST_DOCKER_INTERNAL_IP: 192.168.2.24
      HTTP_EXPOSE: 8143:80
      HTTPS_EXPOSE: 8142:80
      TZ: Europe/Berlin
      VIRTUAL_HOST: nr-repurpose.ddev.site
      XHGUI_PDO_PASS: db
      XHGUI_PDO_USER: db
      XHGUI_SAVE_HANDLER: pdo
    extra_hosts:
      - host.docker.internal=192.168.2.24
    healthcheck:
      test:
        - CMD-SHELL
        - /healthcheck.sh
      timeout: 1m10s
      interval: 1s
      retries: 70
      start_period: 2m0s
      start_interval: 1s
    image: ddev/ddev-xhgui:v1.25.2
    labels:
      com.ddev.app-type: typo3
      com.ddev.approot: /home/sme/p/nr-repurpose/main
      com.ddev.platform: ddev
      com.ddev.site-name: nr-repurpose
      com.ddev.webtag: v1.25.2
    networks:
      ddev_default: null
      default: null
    restart: "no"
    x-ddev:
      describe-url-port: 'Launch: ddev xhgui'
networks:
  ddev_default:
    name: ddev_default
    external: true
  default:
    name: ddev-nr-repurpose_default
    labels:
      com.ddev.app-type: typo3
      com.ddev.approot: /home/sme/p/nr-repurpose/main
      com.ddev.platform: ddev
      com.ddev.site-name: nr-repurpose
      com.ddev.webtag: v1.25.2
volumes:
  database:
    name: nr-repurpose-mariadb
    external: true
  ddev-global-cache:
    name: ddev-global-cache
    external: true
  ddev-ssh-agent_socket_dir:
    name: ddev-ssh-agent_socket_dir
    external: true
